export type ObjectNav = {
    append?: boolean;
    remove?: number;
    next?: string | number;
};
export declare const parseDeep: (fieldPath: string) => ObjectNav[];
export declare const deepGet: <T>(obj: any, fieldPath: string) => T | undefined;
export declare const deepUpdate: (obj: any, fieldPath: string, value: any) => void;
export declare const deepEquals: <T>(object1: T, object2: T) => boolean;
export declare const deepAtLeastEquals: <T>(subset: Partial<T>, superset: Partial<T>, ignore?: (keyof T)[]) => boolean;
export declare const isObject: <T>(object: T) => boolean;
export declare const stripNonAlphaNumericKeys: <T>(obj: T) => T;
export declare const hasDuplicateProperty: (things: Record<string, unknown>[], prop: string) => boolean;
export declare const hasUniqueProperty: (things: Record<string, unknown>[], prop: string) => boolean;
export declare const filterObject: <T>(obj: Record<string, T>, keys: string[]) => Record<string, T>;
export declare const isEmpty: (obj?: unknown | null | undefined) => boolean;
export declare const isNotEmpty: (obj?: unknown | null | undefined) => boolean;
export declare const filterProperties: (obj: Record<string, unknown>, propNames: string[]) => Record<string, unknown>;
export declare const deepEqualsForFields: (o1: Record<string, unknown>, o2: Record<string, unknown>, propNames: string[]) => boolean;
export declare const FN_ALWAYS_TRUE: () => boolean;
export declare const FN_ALWAYS_FALSE: () => boolean;
export declare const immutify: <T>(obj: T) => T;
