import { ZillaClock } from "./time.js";
export declare const capitalize: (s?: string) => string;
export declare const uncapitalize: (s?: string) => string;
export declare const basefilename: (s: string) => string;
export declare const ext: (s: string) => string;
export declare const basefilenameWithoutExt: (s: string) => string;
export declare const dateAsYYYYMMDD: (date: Date) => string;
export declare const dateAsUTCYYYYMMDD: (date: Date) => string;
export declare const nextDateAsYYYYMMDD: (d: string) => string;
export declare const dateAsYYYYMMDDHHmmSS: (date: Date) => string;
export declare const timestampAsYYYYMMDD: (timestamp: number) => string;
export declare const timestampAsUTCYYYYMMDD: (timestamp: number) => string;
export declare const timestampAsYYYYMMDDHHmmSS: (timestamp: number) => string;
export declare const nowAsYYYYMMDD: () => string;
export declare const nowAsYYYYMMDDHHmmSS: () => string;
export declare const sluggize: (name: string, replaceChar?: string) => string;
export declare const hyphenate: (name: string) => string;
export declare const uuidv4: (squeezed?: boolean) => string;
export declare const camel2kebab: (camelCaseString: string) => string;
export declare const camel2snake: (camelCaseString: string) => string;
export declare const kebab2camel: (kebabCaseString: string) => string;
export declare const snake2camel: (kebabCaseString: string) => string;
export declare const hasUpperCase: (str: string) => boolean;
export declare const startsWithPrefix: (s: string, prefixes: string[]) => boolean;
export declare const endsWithSuffix: (s: string, suffixes: string[]) => boolean;
export declare const randomDigit: (min?: number, max?: number) => number;
export declare const randomDigits: (n: number, min?: number, max?: number) => string;
export declare const isOnlyDigits: (s: string) => boolean;
export declare const BASE62_CHARS = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";
export declare const BASE62_CHARS_WITHOUT_SIMILAR_CHARS = "23456789ABCEFGHJKLMNPRSTUVWXYZ";
export declare const VOWEL_CHARS = "AEOIUaeoiu";
export declare const DIGIT_CHARS = "0123456789";
export declare const VOWEL_AND_DIGIT_CHARS: string;
export declare const _randomSafeToken: (n: number, CHARS: string) => string;
export declare const randomSafeToken: (n: number) => string;
export declare const randomSuperSafeToken: (n: number) => string;
export declare const epochToHttpDate: (epoch?: number, clock?: ZillaClock) => string;
export declare const sortWords: (words: string[], dict: string[]) => string[];
export declare const trimSpaces: (str: string) => string;
export declare const trimNonalphanumeric: (str: string) => string;
export declare const getRandomCodePoint: () => number;
export declare const generateRandomString: (length: number) => string;
export declare const sortObj: (o: Record<string, unknown>) => Record<string, unknown>;
export declare const sortedStringify: (obj: Record<string, unknown>) => string;
export declare const jsonHeader: () => {
    "Content-Type": string;
};
export declare const ANSI: {
    RESET: string;
    BOLD: string;
    DIM: string;
    UNDERLINE: string;
    BLINK: string;
    INVERSE: string;
    HIDDEN: string;
    BLACK: string;
    RED: string;
    GREEN: string;
    YELLOW: string;
    BLUE: string;
    MAGENTA: string;
    CYAN: string;
    WHITE: string;
    BRIGHT_BLACK: string;
    BRIGHT_RED: string;
    BRIGHT_GREEN: string;
    BRIGHT_YELLOW: string;
    BRIGHT_BLUE: string;
    BRIGHT_MAGENTA: string;
    BRIGHT_CYAN: string;
    BRIGHT_WHITE: string;
};
export declare const CSS: {
    RESET: string;
    BOLD: string;
    DIM: string;
    UNDERLINE: string;
    BLINK: string;
    INVERSE: string;
    HIDDEN: string;
    BLACK: string;
    RED: string;
    GREEN: string;
    YELLOW: string;
    BLUE: string;
    MAGENTA: string;
    CYAN: string;
    WHITE: string;
    BRIGHT_BLACK: string;
    BRIGHT_RED: string;
    BRIGHT_GREEN: string;
    BRIGHT_YELLOW: string;
    BRIGHT_BLUE: string;
    BRIGHT_MAGENTA: string;
    BRIGHT_CYAN: string;
    BRIGHT_WHITE: string;
};
export declare const REGEX_ARRAY_OF_STRINGS: RegExp;
export declare const REGEX_ARRAY_OF_BOOLEANS: RegExp;
export declare const REGEX_ARRAY_OF_INTEGERS: RegExp;
export declare const REGEX_ARRAY_OF_FLOATS: RegExp;
